import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteShell } from "@/components/SiteShell";
import { SectionEyebrow, OrnamentDivider } from "@/components/Ornaments";
import { ArrowRight, GraduationCap, Heart, Sparkles, ShieldCheck, MessageCircle, Award } from "lucide-react";
import astrologerImg from "@/assets/astrologer.jpg";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "About Sudhansu Suman — Astrosuman" },
      {
        name: "description",
        content:
          "Sudhansu Suman — Nadi Astrologer, Numerologist & Vedic Card Reader. IT graduate turned astrologer, trained under master Umang Taneja.",
      },
      { property: "og:title", content: "About Sudhansu Suman" },
      { property: "og:description", content: "Trained under master astrologer Umang Taneja." },
    ],
  }),
  component: AboutPage,
});

const specialties = [
  { icon: Sparkles, title: "Nadi Astrology", text: "Precision readings rooted in ancient Tamil palm-leaf tradition." },
  { icon: GraduationCap, title: "Numerology", text: "Life Path and Personal Year analysis with practical guidance." },
  { icon: Heart, title: "Vedic Cards", text: "Intuitive insight into your present situation and the next six months." },
  { icon: ShieldCheck, title: "Kundli & Doshas", text: "Full birth-chart readings, Mangal/Kaal Sarp dosha analysis." },
  { icon: Award, title: "Marriage Matching", text: "Honest compatibility analysis — beyond just Guna milan score." },
  { icon: MessageCircle, title: "Targeted Remedies", text: "Simple, sustainable practices — never expensive prescriptions." },
];

const whyChoose = [
  { title: "Hand-written, never templated", text: "Every report is researched on your specific chart. No PDFs generated by software." },
  { title: "Trained, not self-taught", text: "Years of formal study under master astrologer Umang Taneja." },
  { title: "Grounded, not fear-driven", text: "Honest answers, balanced verdicts, and practical remedies you can actually sustain." },
  { title: "Private and respectful", text: "Your birth details and questions are never shared, sold, or used in marketing." },
];

const credentials = [
  "Trained under master Nadi astrologer Umang Taneja",
  "10+ years of consultative practice",
  "500+ readings delivered across India and to diaspora clients abroad",
  "Specialises in Nadi-style precision applied to standard Vedic charts",
  "Engineering graduate — brings analytical rigour to traditional methods",
];

export default function AboutPage() {
  return (
    <SiteShell>
      <section className="bg-cream pt-14 md:pt-20 pb-10 text-center">
        <div className="mx-auto max-w-3xl px-5">
          <SectionEyebrow>About</SectionEyebrow>
          <h1 className="font-display text-[40px] md:text-[60px] leading-[1.05] text-indigo-deep font-semibold">
            An engineer who left tech to{" "}
            <span className="italic text-saffron">read charts.</span>
          </h1>
          <OrnamentDivider />
        </div>
      </section>

      <section className="py-12 md:py-16">
        <div className="mx-auto max-w-6xl px-5 md:px-6 grid md:grid-cols-[1fr_1.2fr] gap-10 lg:gap-16 items-center">
          <div data-animate className="relative">
            <div className="rounded-md overflow-hidden border border-border-warm shadow-warm">
              <img src={astrologerImg} alt="Portrait of Sudhansu Suman" width={800} height={900} loading="lazy" className="w-full h-auto" />
            </div>
          </div>
          <div data-animate data-animate-delay="2">
            <h2 className="font-display text-[30px] md:text-[40px] text-indigo-deep font-semibold leading-tight">
              Sudhansu Suman
            </h2>
            <p className="mt-2 text-saffron font-mono text-sm uppercase tracking-widest">
              Nadi Astrologer · Numerologist · Vedic Card Reader
            </p>
            <div className="mt-6 space-y-5 text-text-body leading-relaxed">
              <p>
                I grew up watching my grandfather read horoscopes for the families in our small town.
                Engineering took me elsewhere for a few years — IT jobs, a settled life — but the old
                pull never quite left.
              </p>
              <p>
                I returned to it formally a decade ago, studying for years under master Nadi astrologer
                Umang Taneja. Today I run Astrosuman full-time, writing every reading by hand.
              </p>
              <p>
                What I promise clients is simple: a reading rooted in your actual chart, written with
                care, free of fear-talk and sales pressure. If your chart says something difficult, I
                tell you. If it says something good, I tell you that too, with the timing.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* SPECIALTIES */}
      <section className="py-16 md:py-20 bg-cream-warm/40">
        <div className="mx-auto max-w-6xl px-5 md:px-6">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <SectionEyebrow>Specialties</SectionEyebrow>
            <h2 className="font-display text-[30px] md:text-[42px] text-indigo-deep font-semibold">
              What I focus on
            </h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {specialties.map(({ icon: Icon, title, text }) => (
              <div key={title} className="bg-white border border-border-light p-7 rounded-md shadow-warm">
                <div className="w-12 h-12 rounded-full bg-saffron-ghost text-saffron inline-flex items-center justify-center mb-4">
                  <Icon size={22} aria-hidden />
                </div>
                <h3 className="font-display text-[20px] text-indigo-deep">{title}</h3>
                <p className="mt-2 text-text-body text-[14.5px] leading-relaxed">{text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* WHY CHOOSE */}
      <section className="py-16 md:py-20">
        <div className="mx-auto max-w-6xl px-5 md:px-6">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <SectionEyebrow>Why clients return</SectionEyebrow>
            <h2 className="font-display text-[30px] md:text-[42px] text-indigo-deep font-semibold">
              What makes Astrosuman different
            </h2>
          </div>
          <div className="grid sm:grid-cols-2 gap-6">
            {whyChoose.map((w) => (
              <div key={w.title} className="bg-white border border-border-light p-7 rounded-md">
                <h3 className="font-display text-[22px] text-indigo-deep">{w.title}</h3>
                <p className="mt-2 text-text-body leading-relaxed">{w.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CREDENTIALS */}
      <section className="py-16 bg-parchment-grain border-y border-border-warm">
        <div className="mx-auto max-w-3xl px-5 md:px-6">
          <SectionEyebrow>Credentials</SectionEyebrow>
          <h2 className="font-display text-[30px] md:text-[40px] text-indigo-deep font-semibold mb-7">
            Background & training
          </h2>
          <ul className="space-y-3">
            {credentials.map((c) => (
              <li key={c} className="flex items-start gap-3 text-text-body">
                <span className="text-saffron mt-1" aria-hidden>✦</span>
                <span>{c}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="bg-indigo-deep py-16 text-center">
        <div className="mx-auto max-w-2xl px-5">
          <h2 className="font-display text-[32px] md:text-[42px] text-cream font-semibold">
            Begin with a reading.
          </h2>
          <p className="mt-3 text-cream/75">Your chart is waiting. Start with what's on your mind.</p>
          <Link
            to="/services"
            className="mt-7 inline-flex items-center gap-2 bg-saffron text-white px-8 py-4 rounded-full font-semibold hover:bg-saffron-hover transition-colors"
          >
            Browse readings <ArrowRight size={16} aria-hidden />
          </Link>
        </div>
      </section>
    </SiteShell>
  );
}
